export const CARDS_ARRAY = [
  {
    id: 129884,
    api_model: 'artworks',
    api_link: 'https://api.artic.edu/api/v1/artworks/129884',
    is_boosted: true,
    title: 'Starry Night and the Astronauts',
    alt_titles: null,
    thumbnail: {
      lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAABw/Zhg/aBRBaBZBahRCaxxBahxEahNIchZJcR9LdB9OdiZIZSBEbShLbjxRZyBPeipRcSpReUpWaitXgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURoMJIDhJAywAcAlEkxhNNTQgAOw==',
      width: 5376,
      height: 6112,
      alt_text:
        'Abstract painting composed of small vertical dabs of multiple shades of blue with a small area of similar strokes of red, orange, and yellow in the upper right.',
    },
    main_reference_number: '1994.36',
    has_not_been_viewed_much: false,
    boost_rank: 1,
    date_start: 1972,
    date_end: 1972,
    date_display: '1972',
    date_qualifier_title: '',
    date_qualifier_id: null,
    artist_display: 'Alma Thomas\nAmerican, 1891–1978',
    place_of_origin: 'United States',
    dimensions: '152.4 × 134.6 cm (60 × 53 in.)',
    medium_display: 'Acrylic on canvas',
    inscriptions: null,
    credit_line:
      'Purchased with funds provided by Mary P. Hines in memory of her mother, Frances W. Pick',
    catalogue_display: null,
    publication_history: null,
    exhibition_history: null,
    provenance_text: null,
    publishing_verification_level: 'Web Basic',
    internal_department_id: 246,
    fiscal_year: 1994,
    fiscal_year_deaccession: null,
    is_public_domain: false,
    is_zoomable: true,
    max_zoom_window_size: -1,
    copyright_notice: null,
    has_multimedia_resources: false,
    has_educational_resources: true,
    has_advanced_imaging: false,
    colorfulness: 53.6375,
    color: {
      h: 45,
      l: 49,
      s: 94,
      percentage: 0.0035946655163737015,
      population: 29,
    },
    latitude: 41.8805769576144,
    longitude: -87.6218733015747,
    latlon: '41.880576957614,41.880576957614',
    is_on_view: true,
    on_loan_display: null,
    gallery_title: 'Gallery 291',
    gallery_id: 25468,
    artwork_type_title: 'Painting',
    artwork_type_id: 1,
    department_title: 'Contemporary Art',
    department_id: 'PC-8',
    artist_id: 44708,
    artist_title: 'Alma Thomas',
    alt_artist_ids: [],
    artist_ids: [44708],
    artist_titles: ['Alma Thomas'],
    category_ids: ['PC-8', 'PC-142', 'PC-825', 'PC-830'],
    category_titles: [
      'Contemporary Art',
      'African American artists',
      'Women artists',
      'African Diaspora',
    ],
    term_titles: [
      'painting',
      'painting (image making)',
      'acrylic paint',
      'patterns',
      'contemporary',
      'canvas',
      'blue (color)',
      'red (color)',
      'orange (color)',
      'yellow (color)',
      'modern and contemporary art',
    ],
    style_id: 'TM-12062',
    style_title: 'contemporary',
    alt_style_ids: [],
    style_ids: ['TM-12062'],
    style_titles: ['contemporary'],
    classification_id: 'TM-9',
    classification_title: 'painting',
    alt_classification_ids: ['TM-155'],
    classification_ids: ['TM-9', 'TM-155'],
    classification_titles: ['painting', 'modern and contemporary art'],
    subject_id: 'TM-12793',
    alt_subject_ids: ['TM-11843', 'TM-11851', 'TM-11905', 'TM-11842'],
    subject_ids: ['TM-12793', 'TM-11843', 'TM-11851', 'TM-11905', 'TM-11842'],
    subject_titles: ['patterns', 'blue (color)', 'red (color)', 'orange (color)', 'yellow (color)'],
    material_id: 'TM-2407',
    alt_material_ids: ['TM-3124'],
    material_ids: ['TM-2407', 'TM-3124'],
    material_titles: ['acrylic paint', 'canvas'],
    technique_id: 'TM-3891',
    alt_technique_ids: [],
    technique_ids: ['TM-3891'],
    technique_titles: ['painting (image making)'],
    theme_titles: ['African American artists', 'Women artists', 'African Diaspora'],
    image_id: 'e966799b-97ee-1cc6-bd2f-a94b4b8bb8f9',
    alt_image_ids: [],
    document_ids: ['0779b4bd-296f-671f-215e-129f2101ad07'],
    sound_ids: [],
    video_ids: [],
    text_ids: ['0779b4bd-296f-671f-215e-129f2101ad07'],
    section_ids: [],
    section_titles: [],
    site_ids: [],
    suggest_autocomplete_boosted: 'Starry Night and the Astronauts',
    suggest_autocomplete_all: [
      {
        input: ['1994.36'],
        contexts: {
          groupings: ['accession'],
        },
      },
      {
        input: ['Starry Night and the Astronauts'],
        weight: 35074,
        contexts: {
          groupings: ['title'],
        },
      },
    ],
    source_updated_at: '2023-04-05T18:07:55-05:00',
    updated_at: '2023-04-05T18:12:21-05:00',
    timestamp: '2023-04-06T07:51:12-05:00',
  },
  {
    id: 28560,
    api_model: 'artworks',
    api_link: 'https://api.artic.edu/api/v1/artworks/28560',
    is_boosted: true,
    title: 'The Bedroom',
    alt_titles: null,
    thumbnail: {
      lqip: 'data:image/gif;base64,R0lGODlhBgAFAPQAAHhwV3N+bnh/aXR8dJtsG6VsAJx4IIp8PIx0QYZ2SoZ/bIx+b3CGboiAQoKAVoWAVpiLYZqNYIiAcoeIc5SNdJeJfJiKfXyCgneAkXmLp3eFqomMgIWJmZOerAAAAAAAACH5BAAAAAAALAAAAAAGAAUAAAUYoMYEXJdhgwBF1wM4RIE01HYYiVJZk7SEADs=',
      width: null,
      height: null,
      alt_text: 'Painting of bedroom, blue walls, green window, tan bed, red bedding.',
    },
    main_reference_number: '1926.417',
    has_not_been_viewed_much: false,
    boost_rank: 2,
    date_start: 1889,
    date_end: 1889,
    date_display: '1889',
    date_qualifier_title: '',
    date_qualifier_id: null,
    artist_display: 'Vincent van Gogh\nDutch, 1853-1890',
    place_of_origin: 'Saint-Rémy-de-Provence',
    dimensions: '73.6 × 92.3 cm (29 × 36 5/8 in.)',
    medium_display: 'Oil on canvas',
    inscriptions: null,
    credit_line: 'Helen Birch Bartlett Memorial Collection',
    catalogue_display: null,
    publication_history:
      'Minneapolis Institute of Arts, "Exhibition of French Paintings from a Well-Known Collection," Bulletin of the Minneapolis Institute of Arts, 14, 4 (April 1925), 31–32.\n\nForbes Watson, "A Note on the Birch Bartlett Collection," The Arts 9, no. 6 (June 1926): 303–06 (ill.), 307–13.\n\nR.M.F., “Van Gogh in Arles,” Bulletin of the Art Institute of Chicago 20, no. 7, (October 1926): 92–94.\n\nMuseo del Palacio de Bellas Artes, Rojo mexicano: la grana cochinilla en el arte, exh. cat. (Ciudad de Mexico: Instituto Nacional de Bellas Artes, 2017), 270, 387 fig. 61.\n\nArt Institute of Chicago Annual Report (Chicago: Art Institute of Chicago, 1926), 54 (ill.).\n\nJ[acob]-B[aart] de la Faille, L\'Oeuvre de Vincent van Gogh: catalogue raisonné (Berlin: G. van Ouest, 1928), vol. 1,  138, no. 484; vol. 2, pl. 134. \n\nArt Institute of Chicago, Modern Paintings in the Helen Birch Bartlett Memorial from the Birch-Bartlett Collection (Chicago: Art Institute of Chicago, 1929), 22–23.\n\nVincent van Gogh, Further Letters to His Brother, 1886–1889 (London: Constable and Co., 1929), 234–35, 280, 371–72.\n\nArt Institute of Chicago, A Guide to the Paintings in the Permanent Collection (Chicago: Art Institute of Chicago, 1932), 27 (ill.).\n\nArt Institute of Chicago, A Brief Guide to the Collections (Chicago: Art Institute of Chicago, 1935), 30 (ill.), 31.\n\nW. Scherjon and Jos. de Gruyter, Vincent van Gogh\'s Great Period: Arles, St. Rémy and Auvers sur Oise (Complete Catalog) (Amsterdam: De Spieghel, 1937), 140 (ill.), no. 12.\n\nJ[acob]-B[aart] de la Faille, Vincent van Gogh, trans. Prudence Montagu-Pollock (New York: French and European Publications; Paris: Hyperion, 1938), 362 (ill.), no. 510.\n\nArt Institute of Chicago, Masterpiece of the Month, Notes and Bibliography (Chicago: Art Institute of Chicago, 1938), 18–19 (ill.). \n\nArt Institute of Chicago, A Brief Guide to the Collections (Chicago: Art Institute of Chicago, 1941), 36 (ill.), 37.\n\nArt Institute of Chicago, A Brief Guide to the Collections (Chicago: Art Institute of Chicago, 1945), 40 (ill.).\n\nArt Institute of Chicago, Modern Paintings in the Helen Birch Bartlett Memorial from the Birch-Bartlett Collection (Chicago: Art Institute of Chicago, 1946), 18–19 (ill.).\n\nLouis Hautecoeur, Van Gogh (Monaco: Les Documents d\'Art, 1946), 78, 144.\n\nEgbert Jacobson, Basic Color (Paul Theobald, 1948),174–76 (ill.).\n\nArt Institute of Chicago, A Brief Guide to the Collections (Chicago: Art Institute of Chicago, 1948), p. 37 (ill.).\n\nMeyer Schapiro, Vincent van Gogh, The Library of Great Painters (New York: Harry N. Abrams, 1950), 78–79 (ill.).\n\nCharles Fabens Kelley, “Chicago: record years,” Art News 51, no. 4 (June–August 1952): 52–65, 106–08, 109 (ill.), 110–11.\n\nLawrence and Elisabeth Hanson, Passionate Pilgrim: The Life of Vincent Van Gogh (New York: Random House, 1955), 209–10.\n\nArt Institute of Chicago, A Brief Guide to the Collections (Chicago: Art Institute of Chicago, 1956), 36 (ill.).\n\nArt Institute of Chicago, Paintings in the Art Institute of Chicago: A Catalogue of the Picture Collection (Chicago: Art Institute of Chicago, 1961), 198, 328 (ill.).\n\nFrederick A. Sweet, “Great Chicago Collectors,” Apollo 84 (September 1966): 194, fig. 16, 197.\n\nJacob-Baart de la Faille, The Works of Vincent van Gogh, His Paintings and Drawings (New York: Reynal, 1970), 284 (ill), 285, no. F484.\n\nJohn Maxon, The Art Institute of Chicago (New York: Harry N. Abrams, 1970), 93 (ill.), 94 [repr. 1977, 1987].\n\nPaolo Lecaldano, Tout l\'oeuvre peint de Van Gogh, vol. 2: 1888–1890, trans. Simone Darses, vol. 2 (Paris: Flammarion, 1971), 220 (ill.), 221, no. 690.\n\nKatharine Kuh, “These Are A Few of My Favorite Things,” Chicago Tribune Magazine, April 23, 1972, 32.\n\nMike Samuels, M.D. and Nancy Samuels, Seeing with the Mind’s Eye: The History, Techniques and Uses of Visualization (New York: Random House, 1975), 76, pl. 2.\n\nJohn L. Word, “A Reexamination of Van Gogh’s Pictorial Space,” The Art Bulletin 58, no. 4 (December 1976): 593–604. \n\nGuy Hubbard and Mary J. Rouse, ART: Discovering and Creating (Westchester, IL: Benefic Press, 1977), 102 (ill.).\n\nPaolo Lecaldano, L’opera pittorica completa di Van Gogh, vol. 2 (Milan: Rizzoli Editore, 1977), 220 (ill.), 221, no. 690.\n\nJanice Feldstein and Maureen Smith, The Art Institute of Chicago: 100 Masterpieces (Chicago: Art Institute of Chicago; distributed by Rand McNally, 1978), 116–17 (color ill.), no. 69. \n\nRobert H. Pelfrey and Mary Hall-Pelfrey, Art and Mass Media (New York: Harper & Row, 1985), 126 pl. 18, 182–83 fig. 7.23), 184.\n\nPeter C. Sutton, A Guide to Dutch Art in America (Washington, D.C.: Netherlands-American Amity Trust; Grand Rapids: Eerdmans, 1986), 54 fig. 77.\n\nRichard R. Brettell, “The Bartletts and the ‘Grande Jatte’: Collecting Modern Painting in the 1920s,” Art Institute of Chicago Museum Studies 12, no. 2 (1986): 105, 111.\n\nRichard R. Brettell, “Van Gogh’s Bedroom at Arles: the Problem of Priority,” Art Institute of Chicago Museum Studies 12, 2 (1986): pp. 136–37 (ill.), 138–51.\n\nJames N. Wood and Katharine C. Lee, eds., Master Paintings in The Art Institute of Chicago (Chicago Art Institute of Chicago, 1988), 65 (ill.).\n\nWalter Feilchendeldt, Vincent van Gogh and Paul Cassirer, Berlin: the reception of Van Gogh in Germany from 1901 to 1914 (Zwolle: Van Gogh Museum, 1988), 98 (ill.).\n\nJan Hulsker, “Bedroom Problems,” Simiolus, 18, 4 (1988): 257–59 (ill.), 260–61.\n\nIngo F. Walther and Rainer Metzger, Vincent Van Gogh Sämtliche Gemälde (Cologne: Benedikt Taschen Verlag, 1989), 441, 442, 548, 549 (color ill.).\n\nGene A. Mittler, Art in Focus (New York: Glencoe Publishing Company, 1989), p. 319, fig. 17.6.\n\nRichard Thomson, “State of the Art Van Gogh,” Apollo 132, no. 341(July 1990): 41 fig. 14, 42. \n\n“Vincent van Gogh Retrospective Exhibition,” Van Gogh Bulletin 5, no. 1 (1990): 5 (color ill.), 6.\n\nJan Hulsker, The New Complete Van Gogh, Enlarged Edition of the Catalogue Raisonné of the Works of Vincent van Gogh (Aldershot, England; Burlington, VT: J.M. Meulenhoff; Philadelphia: John Benjamins Pub. Co., 1996), 404-09 no. 1771, 496n1771.\n\nMark Rosenthal, The Robert and Jane Meyerhoff Collection, 1945 to 1995, exh. cat. (Washington, D.C., National Gallery of Art, 1996), 123–29 fig. 11. \n\nSculpture Foundation, Solid Impressions: J. Seward Johnson, Jr. (Hamilton, NJ: The Sculpture Foundation, 2002), 26 (color ill.), 27–29.\n\nPetra ten-Doesschate Chu, "The Reality of Illusion, The Illusion of Reality," in Beyond the Frame: Impressionism Revisited: The Sculptures of J. Seward Johnson, Jr., exh. cat. (Boston: Bulfinch Press; Washington, D.C.: In association with the Corcoran Gallery of Art, 2003), 11 (color ill.), 12, 15–18.\n\nRichard R. Brettell, "A View from Portland: 110 Years of Modern French Art in Portland," in Paris to Portland: Impressionist and Post Impressionist Masters in Portland Collections, exh. cat. (Portland: Portland Art Museum, 2003), p. 33, fig. 3. \n\nKimberly A. Smith, Between Ruin and Renewal: Egon Schiele\'s Landscapes (New Haven: Yale University Press, 2004), 30 fig. 15, 31.\n\nKatharine Kuh, My Love Affair with Modern Art: Behind the Scenes with a Legendary Curator (New York: Arcade Publishing, 2006), 52–53 (ill.), 91–94.\n\nJill Lloyd, Vincent van Gogh and Expressionism, exh. cat. (Ostfildern: Hatje Cantz Verlag; Amsterdam: Van Gogh Museum, 2006), 115–16, 122 (color ill.), 123–24.\n\nTsukasa Kodera, Vincent Willem van Gogh (Tokyo: Shogakukan, 2006), 16 (color ill.).\n\nLeo Jansen, Hans Luijten, and Nienke Bakker, eds., Vincent van Gogh, The Letters: The Complete Illustrated and Annotated Edition, vol 5: Saint-Rémy-de-Provence - Auvers-sur-Oise, 1889–1890 (Amsterdam: Van Gogh Museum; The Hague: Huygens Institute; Brussels: Mercatorfonds, 2009), 79 fig. 2, 80–88.\n\nMarika Spring, Helen Howard, Jo Kirby, Joseph Padfield, David Peggie, Ashok Roy, and Anne Stephenson-Wright, Studying Old Master Paintings: Technology and Practice (London: Archetype Publications: In association with the National Gallery, 2011), 237–38 fig. 2, 239–43.\n\nWalter Feilchenfeldt, Vincent van Gogh: Die Gemälde 1886–1890 Händler, Sammler, Ausstellungen Die Frühen Provenienzen (Wädenswil, Switzerland: Nimbus, Kunst und Bücher, 2009), 118 (color ill.).\n\nWalter Feilchendeldt, Vincent van Gogh: The years in France, Complete paintings 1886-1890. Dealers, collectors, exhibitions, provenance (London: Philip Wilson, 2013), 120 (color ill.).\n\nWilliam Rathbone, Marcia Steele, H. Travers Newton, and Galina K. Olmsted, "The Bedroom," Van Gogh Repetitions, exh. cat. (The Phillips Collection/The Cleveland Museum of Art, 2013), pp. 82 (color ill.), 83–89, fig. 38.\n\nGloria Groom, ed., Van Gogh\'s Bedrooms, exh. cat. (New Haven and London: Art Institute of Chicago, Yale University Press, 2016), plate 26.\n\nJill Shaw, ed., Van Gogh in America, exh. cat. (Detroit: Detroit Institute of Arts; New Haven: Yale University Press, 2022), 82, 128, 130, 131 pl. 45, 148, 163, 165n3, 209-10, 218, 222, 228n80, 228 n139, 228n141, 238 cat. 53.',
    exhibition_history:
      "Paris, Galerie Vollard, 1895, no cat.\n\nParis, Galerie Bernheim-Jeune, Vincent van Gogh, Mar. 15–31, 1901, cat. 19, as La Chambre de Vincent à Arles.\n\nVienna Secession, Internationalen Kunstschau, May–Oct. 1909, room 14, cat. 1, as Das Schlafzimmer.\n\nBerlin, Paul Cassirer, Zehnte Ausstellung: Vincent van Gogh: 30 März 1853–29 Juli 1890, May–June 1914, cat. 53, as Das Schlafzimmer.\n\nNew York, Museum of Modern Art, First Loan Exhibition: Cézanne, Gauguin, Seurat, Van Gogh, Nov. 7–Dec. 7, 1929, cat. 79, as Van Gogh's Room at Arles (La Chambre à Arles).\n\nArt Institute of Chicago, A Century of Progress, June 1–Nov. 1, 1933, cat. 376.\n\nArt Institute of Chicago, A Century of Progress, June 1–Nov. 1, 1934, cat. 310.\n\nToledo Museum of Art, French Impressionists and Post Impressionists, Nov. 1934, cat. 24.\n\nArt Institute of Chicago, Paintings and Drawings by Vincent van Gogh, lent through the Museum of Modern Art, N.Y., Aug. 26–Sep. 23, 1936, no cat.\n\nAmsterdam, Van Gogh Museum, Vincent van Gogh Paintings, Mar. 30–July 29, 1990, cat. 7.\n\nEssen, Museum Folkwang, Vincent van Gogh und die Moderne 1890–1914, Aug. 11–Nov. 4, 1990, cat. 40, as Das Schlafzimmer; Amsterdam, Van Gogh Museum, Nov. 16, 1990–Feb. 18, 1991.\n\nArt Institute of Chicago, Van Gogh and Gauguin: The Studio of the South, Sep. 22, 2001–Jan. 13, 2002, cat. 120.\n\nAmsterdam, Van Gogh Museum, Van Gogh and Expressionism, Nov. 24, 2006-Mar. 2, 2007; New York, Neue Gallery, Mar. 23-July 2, 2007 [New York only].\n\nFort Worth, TX, Kimbell Museum of Art, The Impressionists: Master Paintings from the Art Institute of Chicago, June 29–Nov. 2, 2008, cat. 58.\n\nAmsterdam, Van Gogh Museum, Van Gogh at Work, Sep. 1, 2013 - Jan. 13, 2014, cat. 266.\n\nArt Institute of Chicago, Van Gogh’s Bedrooms, Feb. 14–May 10, 2016, no cat. no., plate 26.\n\nDetroit Institute of Art, Van Gogh and America, Oct. 2, 2022 - Jan. 22, 2023, cat. 53.",
    provenance_text:
      'The artist; sent to his brother, Theo van Gogh (died 1891), Paris, Dec. 18, 1889 [Letter 829 from Vincent van Gogh to Theo van Gogh, Dec. 19, 1889, notes that The Bedroom was sent the day before]; by descent to Johanna van Gogh-Bonger (died 1925), the Netherlands, 1891; sold to Jos Hessel, Paris, by 1901 [Paris 1901]. Carl Reininghaus, Vienna, by 1909, to at least 1914 [Vienna 1909; Berlin 1914]. Paul Rosenberg, Paris and New York, by 1926; sold to Frederic Clay Bartlett, Chicago, Dec. 1926 [receipt and correspondence in curatorial object file]; given to the Art Institute of Chicago, 1926.',
    publishing_verification_level: 'Web Cataloged',
    internal_department_id: 14,
    fiscal_year: 1926,
    fiscal_year_deaccession: null,
    is_public_domain: true,
    is_zoomable: true,
    max_zoom_window_size: -1,
    copyright_notice: null,
    has_multimedia_resources: true,
    has_educational_resources: false,
    has_advanced_imaging: false,
    colorfulness: 65.636,
    color: {
      h: 40,
      l: 33,
      s: 84,
      percentage: 0.30623617995004176,
      population: 1709,
    },
    latitude: 41.8796324221449,
    longitude: -87.6228838786482,
    latlon: '41.879632422145,41.879632422145',
    is_on_view: true,
    on_loan_display: null,
    gallery_title: 'Gallery 241',
    gallery_id: 2147479705,
    artwork_type_title: 'Painting',
    artwork_type_id: 1,
    department_title: 'Painting and Sculpture of Europe',
    department_id: 'PC-10',
    artist_id: 40610,
    artist_title: 'Vincent van Gogh',
    alt_artist_ids: [],
    artist_ids: [40610],
    artist_titles: ['Vincent van Gogh'],
    category_ids: ['PC-10', 'PC-831'],
    category_titles: ['Painting and Sculpture of Europe', 'Essentials'],
    term_titles: [
      'oil on canvas',
      'oil painting',
      'Post-Impressionism',
      'interiors',
      'oil paint (paint)',
      'painting (image making)',
      'painting',
      'european painting',
      'domestic scenes',
      'Century of Progress',
      "world's fairs",
      "Chicago World's Fairs",
      'beds',
      'bedrooms',
    ],
    style_id: 'TM-7547',
    style_title: 'Post-Impressionism',
    alt_style_ids: [],
    style_ids: ['TM-7547'],
    style_titles: ['Post-Impressionism'],
    classification_id: 'TM-66',
    classification_title: 'oil on canvas',
    alt_classification_ids: ['TM-9', 'TM-54'],
    classification_ids: ['TM-66', 'TM-9', 'TM-54'],
    classification_titles: ['oil on canvas', 'painting', 'european painting'],
    subject_id: 'TM-12285',
    alt_subject_ids: ['TM-10120', 'TM-12169', 'TM-11299', 'TM-12176', 'TM-12436', 'TM-12850'],
    subject_ids: [
      'TM-12285',
      'TM-10120',
      'TM-12169',
      'TM-11299',
      'TM-12176',
      'TM-12436',
      'TM-12850',
    ],
    subject_titles: [
      'interiors',
      'domestic scenes',
      'Century of Progress',
      "world's fairs",
      "Chicago World's Fairs",
      'beds',
      'bedrooms',
    ],
    material_id: 'TM-2451',
    alt_material_ids: [],
    material_ids: ['TM-2451'],
    material_titles: ['oil paint (paint)'],
    technique_id: 'TM-4273',
    alt_technique_ids: ['TM-3891'],
    technique_ids: ['TM-4273', 'TM-3891'],
    technique_titles: ['oil painting', 'painting (image making)'],
    theme_titles: ['Essentials'],
    image_id: '25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e',
    alt_image_ids: [],
    document_ids: ['02e976d2-8c4a-3cc2-9d2b-3cee40fe8291', 'bc6092c7-006c-a5d2-8ea1-ce5308596178'],
    sound_ids: ['02e976d2-8c4a-3cc2-9d2b-3cee40fe8291'],
    video_ids: [],
    text_ids: [],
    section_ids: [],
    section_titles: [],
    site_ids: [],
    suggest_autocomplete_boosted: 'The Bedroom',
    suggest_autocomplete_all: [
      {
        input: ['1926.417'],
        contexts: {
          groupings: ['accession'],
        },
      },
      {
        input: ['The Bedroom'],
        weight: 225938,
        contexts: {
          groupings: ['title'],
        },
      },
    ],
    source_updated_at: '2023-02-14T10:49:17-06:00',
    updated_at: '2023-03-22T23:15:55-05:00',
    timestamp: '2023-04-06T07:51:12-05:00',
  },
  {
    id: 229393,
    api_model: 'artworks',
    api_link: 'https://api.artic.edu/api/v1/artworks/229393',
    is_boosted: true,
    title: 'Untitled',
    alt_titles: null,
    thumbnail: {
      lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAAD4uK1MvI1k+OlhANWRCOmdIQmlKRnRPT21lVWllWmlgXnhgW3JlZXZxaIBmWJd8c6CFbZWdl7WTgKywrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAUR4PQ4EnM0kAEMiBAUyUIoUQgAOw==',
      width: 5467,
      height: 6765,
      alt_text:
        'Abstract painting of several various-colored and overlapping rings and circles, looser brushstrokes drape across the circles like winding thread.',
    },
    main_reference_number: '2015.176',
    has_not_been_viewed_much: false,
    boost_rank: 10,
    date_start: 1964,
    date_end: 1964,
    date_display: '1964',
    date_qualifier_title: '',
    date_qualifier_id: null,
    artist_display: 'Tanaka Atsuko\nJapanese, 1932-2005',
    place_of_origin: null,
    dimensions: '90.5 × 72.5 cm (35 5/8 × 28 1/2 in.)',
    medium_display: 'Enamel on canvas',
    inscriptions: null,
    credit_line: 'Through prior purchase from the Mary and Leigh Block Fund',
    catalogue_display: null,
    publication_history: null,
    exhibition_history: null,
    provenance_text: null,
    publishing_verification_level: 'Web Basic',
    internal_department_id: 246,
    fiscal_year: 2015,
    fiscal_year_deaccession: null,
    is_public_domain: false,
    is_zoomable: false,
    max_zoom_window_size: 843,
    copyright_notice: null,
    has_multimedia_resources: true,
    has_educational_resources: false,
    has_advanced_imaging: false,
    colorfulness: 65.9821,
    color: {
      h: 10,
      l: 43,
      s: 90,
      percentage: 0.06039244855552863,
      population: 531,
    },
    latitude: null,
    longitude: null,
    latlon: null,
    is_on_view: false,
    on_loan_display: null,
    gallery_title: null,
    gallery_id: null,
    artwork_type_title: 'Painting',
    artwork_type_id: 1,
    department_title: 'Contemporary Art',
    department_id: 'PC-8',
    artist_id: 58851,
    artist_title: 'Tanaka Atsuko',
    alt_artist_ids: [],
    artist_ids: [58851],
    artist_titles: ['Tanaka Atsuko'],
    category_ids: ['PC-8', 'PC-825'],
    category_titles: ['Contemporary Art', 'Women artists'],
    term_titles: ['Gutai group', 'painting'],
    style_id: 'TM-13467',
    style_title: 'Gutai group',
    alt_style_ids: [],
    style_ids: ['TM-13467'],
    style_titles: ['Gutai group'],
    classification_id: 'TM-9',
    classification_title: 'painting',
    alt_classification_ids: [],
    classification_ids: ['TM-9'],
    classification_titles: ['painting'],
    subject_id: null,
    alt_subject_ids: [],
    subject_ids: [],
    subject_titles: [],
    material_id: null,
    alt_material_ids: [],
    material_ids: [],
    material_titles: [],
    technique_id: null,
    alt_technique_ids: [],
    technique_ids: [],
    technique_titles: [],
    theme_titles: ['Women artists'],
    image_id: '7690dd6e-05ed-773c-a80e-e7cc4eb879cc',
    alt_image_ids: [],
    document_ids: [],
    sound_ids: [],
    video_ids: [],
    text_ids: [],
    section_ids: [7346],
    section_titles: ['125  Tanaka Atsuko, Untitled, 1964'],
    site_ids: [],
    suggest_autocomplete_boosted: 'Untitled',
    suggest_autocomplete_all: [
      {
        input: ['2015.176'],
        contexts: {
          groupings: ['accession'],
        },
      },
      {
        input: ['Untitled'],
        weight: 16843,
        contexts: {
          groupings: ['title'],
        },
      },
    ],
    source_updated_at: '2022-09-21T19:19:31-05:00',
    updated_at: '2023-03-22T23:08:32-05:00',
    timestamp: '2023-04-06T07:51:12-05:00',
  },
];
