export const CARD_EXAMPLE = {
  id: 16295,
  api_model: 'artworks',
  api_link: 'https://api.artic.edu/api/v1/artworks/16295',
  is_boosted: false,
  title: 'Virgin and Child',
  alt_titles: null,
  thumbnail: {
    lqip: 'data:image/gif;base64,R0lGODlhBAAFAPQAAF8rHWQzHkI3ImQsIllHJVtPN2BHLGVKKWFOLXJELWpPMW1XNGFVPnRTPnFnR3FuUnp+XoFXPINyS56HZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAAAAAAALAAAAAAEAAUAAAURIHEUjxAxUDA4CNBMiSEtSggAOw==',
    width: 635,
    height: 768,
    alt_text: 'A work made of oil on panel.',
  },
  main_reference_number: '1933.1050',
  has_not_been_viewed_much: false,
  boost_rank: null,
  date_start: 1480,
  date_end: 1490,
  date_display: '1485/90',
  date_qualifier_title: '',
  date_qualifier_id: null,
  artist_display: 'Hans Memling\nNetherlandish, 1435/40–1494',
  place_of_origin: 'Netherlands',
  dimensions:
    'Frame: 41.1 × 33.4 cm (16 3/16 × 13 1/8 in.); Painted surface: 34.5 × 26.8 cm (14 1/16 × 10 1/2 in.)',
  medium_display: 'Oil on panel',
  inscriptions: null,
  credit_line: 'Mr. and Mrs. Martin A. Ryerson Collection',
  catalogue_display: null,
  publication_history:
    'Henri Hymans, “Notes sur quelques oeuvres d’art conservées\nen Espagne,” Gazette des Beaux-Arts, 3rd ser., 12 (1894), pp. 159–60.',
  exhibition_history: 'Madrid, Exposición histórico-Europea, 1892–93.5',
  provenance_text:
    'Probably a Spanish convent [according to invoice from Steinmeyer, Paris, June 23, 1913 in curatorial file]. Private collection, Spain, by 1892 [according to Hymans 1894, p. 159, it was lent to the 1892–93 Madrid exhibition by a private owner].',
  publishing_verification_level: 'Web Cataloged',
  internal_department_id: 14,
  fiscal_year: 1933,
  fiscal_year_deaccession: null,
  is_public_domain: true,
  is_zoomable: true,
  max_zoom_window_size: -1,
  copyright_notice: null,
  has_multimedia_resources: true,
  has_educational_resources: false,
  has_advanced_imaging: false,
  colorfulness: 50.6198,
  color: {
    h: 359,
    l: 33,
    s: 68,
    percentage: 0.03744795664410485,
    population: 322,
  },
  latitude: 41.8794811464592,
  longitude: -87.6233499124645,
  latlon: '41.879481146459,41.879481146459',
  is_on_view: true,
  on_loan_display: null,
  gallery_title: 'Gallery 202',
  gallery_id: 2147483640,
  artwork_type_title: 'Painting',
  artwork_type_id: 1,
  department_title: 'Painting and Sculpture of Europe',
  department_id: 'PC-10',
  artist_id: 35736,
  artist_title: 'Hans Memling',
  alt_artist_ids: [],
  artist_ids: [35736],
  artist_titles: ['Hans Memling'],
  category_ids: ['PC-10'],
  category_titles: ['Painting and Sculpture of Europe'],
  term_titles: [
    'oil on panel',
    'Century of Progress',
    'painting',
    'european painting',
    "world's fairs",
    "Chicago World's Fairs",
  ],
  style_id: null,
  style_title: null,
  alt_style_ids: [],
  style_ids: [],
  style_titles: [],
  classification_id: 'TM-80',
  classification_title: 'oil on panel',
  alt_classification_ids: ['TM-9', 'TM-54'],
  classification_ids: ['TM-80', 'TM-9', 'TM-54'],
  classification_titles: ['oil on panel', 'painting', 'european painting'],
  subject_id: 'TM-12169',
  alt_subject_ids: ['TM-11299', 'TM-12176'],
  subject_ids: ['TM-12169', 'TM-11299', 'TM-12176'],
  subject_titles: ['Century of Progress', "world's fairs", "Chicago World's Fairs"],
  material_id: null,
  alt_material_ids: [],
  material_ids: [],
  material_titles: [],
  technique_id: null,
  alt_technique_ids: [],
  technique_ids: [],
  technique_titles: [],
  theme_titles: [],
  image_id: '72083f93-6fe2-bfa8-b9a0-82e50c123015',
  alt_image_ids: [],
  document_ids: ['b3d2fcbb-03d5-65ad-1464-6c95bf8ada99'],
  sound_ids: ['b3d2fcbb-03d5-65ad-1464-6c95bf8ada99'],
  video_ids: [],
  text_ids: [],
  section_ids: [],
  section_titles: [],
  site_ids: [],
  suggest_autocomplete_all: [
    {
      input: ['1933.1050'],
      contexts: {
        groupings: ['accession'],
      },
    },
    {
      input: ['Virgin and Child'],
      weight: 5828,
      contexts: {
        groupings: ['title'],
      },
    },
  ],
  source_updated_at: '2023-01-06T11:17:27-06:00',
  updated_at: '2023-03-22T23:03:43-05:00',
  timestamp: '2023-04-05T06:23:56-05:00',
};
